# ELYTRA SIZING CONFIGURATION
# All simulation units are in SI

# ---- UNITS ---- #
PSIA_TO_PA = 6894.76
LBF_TO_N = 4.44822
LBM_TO_KG = 0.453592
IN_TO_M = 0.0254
FT_TO_M = 0.3048


# ---- LAUNCH INPUTS ---- #
INITIAL_ALTITUDE = 2050 * FT_TO_M


# ---- BOATTAIL ---- #
BOATTAIL_MASS = 10 * LBM_TO_KG


# ---- ENGINE ---- #
CHAMBER_PRESSURE = 250 * PSIA_TO_PA
EXIT_PRESSURE = 7 * PSIA_TO_PA
MIXTURE_RATIO = 2
THRUST = 3000 * LBF_TO_N
CHAMBER_LENGTH = 8 * IN_TO_M
CONTRACTION_RATIO = 3.5
THRUST_COEFFICIENT_EFFICIENCY = 1.0
NFZ = 2