# ELYTRA SIZING CONFIGURATION
# All simulation units are in SI

# ---- UNITS ---- #
PSIA_TO_PA = 6894.76
LBF_TO_N = 4.44822
LBM_TO_KG = 0.453592
IN_TO_M = 0.0254
IN3_TO_M3 = 1.63871e-5
FT_TO_M = 0.3048


# ---- SOLVER INPUTS ---- #
DT = 0.0005
T_FINAL = 0.1


# ---- PROPELLANTS ---- #
FUEL = 'RP-1'
OXIDIZER = 'LOX'
FUEL_TEMPERATURE = 298.15
OXIDIZER_TEMPERATURE = 90.17
FUEL_DENSITY = 800
OXIDIZER_DENSITY = 1140
FUEL_MASS_FLOW = 1.98
OXIDIZER_MASS_FLOW = 3.96


# ---- LAUNCH INPUTS ---- #
INITIAL_ALTITUDE = 2050 * FT_TO_M


# ---- BOATTAIL ---- #
BOATTAIL_MASS = 10 * LBM_TO_KG


# ---- INJECTOR ---- #
FUEL_MANIFOLD_PRESSURE = 300 * PSIA_TO_PA 
OXIDIZER_MANIFOLD_PRESSURE = 300 * PSIA_TO_PA
FUEL_STIFFNESS = 0.2
OXIDIZER_STIFFNESS = 0.2
FUEL_MANIFOLD_VOLUME = 40 * IN3_TO_M3
OXIDIZER_MANIFOLD_VOLUME = 40 * IN3_TO_M3
INJECTOR_MASS = 30 * LBM_TO_KG

# ---- ENGINE ---- #
CHAMBER_PRESSURE = 250 * PSIA_TO_PA
EXIT_PRESSURE = 7 * PSIA_TO_PA
MIXTURE_RATIO = 2
THRUST = 3000 * LBF_TO_N
CHAMBER_LENGTH = 8 * IN_TO_M
CONTRACTION_RATIO = 3.5
CHARACTERSTIC_VELOCITY_EFFICIENCY = 0.9
THRUST_COEFFICIENT_EFFICIENCY = 0.95
NFZ = 2
ENGINE_MASS = 60 * LBM_TO_KG