"""Matplotlib plotting API for saved sensitivity data; requires no flight model."""
from __future__ import annotations

import re
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


def _filename(*parts: str) -> str:
    slug = '_'.join(re.sub(r'[^a-zA-Z0-9]+', '_', str(part)).strip('_')
                    for part in parts)
    return slug.lower() + '.png'


def _axes(ax, figsize):
    if ax is None:
        fig, ax = plt.subplots(figsize=figsize)
        return fig, ax, True
    return ax.figure, ax, False


def _axis_setting(setting, axis_name):
    """Accept a numeric display divisor OR a Matplotlib axis-scale name.

    Numeric settings divide plotted coordinates without changing saved sweep
    data. String settings preserve the older linear/log/symlog behavior.
    """
    if isinstance(setting, str):
        return setting, 1.0
    if isinstance(setting, (bool, np.bool_)) or not isinstance(setting, (int, float, np.number)):
        raise TypeError(f'{axis_name} must be a positive numeric divisor or a Matplotlib scale name')
    divisor = float(setting)
    if not np.isfinite(divisor) or divisor <= 0:
        raise ValueError(f'{axis_name} numeric divisor must be positive and finite')
    return 'linear', divisor


def _destination(results, fig, save, filename, file_format, default_name):
    """Resolve image destination without changing the legacy save=path behavior."""
    if save is False:
        if filename is not None:
            raise ValueError('filename cannot be used with save=False')
        return None
    if save is None and filename is None:
        return None
    if filename is not None:
        if save not in (None, True):
            raise ValueError('Specify either filename=... or save=path, not both')
        destination = Path(filename).expanduser()
        if not destination.is_absolute():
            destination = Path(results.folder) / 'plots' / destination
    elif save is True:
        destination = Path(results.folder) / 'plots' / default_name
    elif isinstance(save, (str, Path)):
        destination = Path(save).expanduser()
    else:
        raise TypeError('save must be None, bool, str, or pathlib.Path')

    if file_format is not None:
        image_format = str(file_format).strip().lower().lstrip('.')
        destination = destination.with_suffix('.' + image_format)
    else:
        if not destination.suffix:
            destination = destination.with_suffix('.png')
        image_format = destination.suffix.lower().lstrip('.')

    formats = fig.canvas.get_supported_filetypes()
    if image_format not in formats:
        raise ValueError(f'Unsupported image format {image_format!r}; supported formats: {sorted(formats)}')
    return destination


def _finish(results, fig, ax, *, default_xlabel, default_ylabel, default_name,
            title=None, xlabel=None, ylabel=None, xlim=None, ylim=None,
            xscale='linear', yscale='linear', grid=True, legend=None,
            legend_title=None, save=None, filename=None, file_format=None,
            show=None, dpi=160, owns_axes=True):
    """Apply figure settings and save/show the figure, returning it to callers.

    save=True writes under results.folder/plots/ using an autogenerated name.
    filename='name.jpg' saves under that folder; absolute filenames are allowed.
    save=path preserves the original explicit-path behavior (relative to CWD).
    file_format='jpeg' overrides the output extension where provided.
    xlim/ylim are interpreted in the plotted (possibly divided) display units.
    """
    ax.set(xlabel=default_xlabel if xlabel is None else xlabel,
           ylabel=default_ylabel if ylabel is None else ylabel,
           xscale=xscale, yscale=yscale)
    if title is not None:
        ax.set_title(title)
    if xlim is not None:
        ax.set_xlim(xlim)
    if ylim is not None:
        ax.set_ylim(ylim)
    ax.grid(bool(grid), alpha=0.3)

    handles, labels = ax.get_legend_handles_labels()
    if legend == 'baseline':
        baseline_handles = [handle for handle, label in zip(handles, labels)
                            if label == 'baseline']
        if baseline_handles:
            ax.legend(handles=baseline_handles, title=legend_title, loc='upper left')
    else:
        if legend is None:
            legend = bool(handles)
        if legend and handles:
            ax.legend(title=legend_title)
        elif not legend and ax.get_legend() is not None:
            ax.get_legend().remove()

    if owns_axes:
        fig.tight_layout()

    destination = _destination(results, fig, save, filename, file_format, default_name)
    if destination is not None:
        destination.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(destination, dpi=dpi, bbox_inches='tight')

    if show is None:
        show = destination is None and owns_axes
    if show:
        plt.show()
    return fig


def _plot_line_or_scatter(ax, x, y, *, kind, default_kind='line', style=None):
    style = dict(style or {})
    if kind == 'auto':
        kind = default_kind
    # Black is the default for an individual curve; users can still override color.
    style.setdefault('color', 'black')
    if kind == 'line':
        style.setdefault('marker', 'o')
        ax.plot(x, y, **style)
    elif kind == 'scatter':
        ax.scatter(x, y, **style)
    else:
        raise ValueError("kind must be 'auto', 'line', or 'scatter'")


def _color_map(values, cmap, color_scale):
    if not np.isfinite(color_scale) or color_scale == 0:
        raise ValueError('color_scale must be nonzero and finite')
    scaled = np.asarray(values, dtype=float) / color_scale
    if not np.all(np.isfinite(scaled)):
        raise ValueError('Cannot draw colorbar for non-finite parameter values')
    low, high = float(np.min(scaled)), float(np.max(scaled))
    if low == high:
        low -= 0.5
        high += 0.5
    norm = mpl.colors.Normalize(vmin=low, vmax=high)
    colormap = plt.get_cmap(cmap)
    return colormap, norm


def _add_colorbar(fig, ax, colormap, norm, label):
    mappable = mpl.cm.ScalarMappable(cmap=colormap, norm=norm)
    mappable.set_array([])
    fig.colorbar(mappable, ax=ax, label=label, pad=0.025)


def _field_spec(spec, name):
    """Normalize field name, ordered list, or {field: legend_label}."""
    if spec is None:
        return []
    if isinstance(spec, str):
        return [(spec, spec)]
    if isinstance(spec, dict):
        pairs = list(spec.items())
    elif isinstance(spec, (tuple, list)):
        pairs = [(field, field) for field in spec]
    else:
        raise TypeError(f'{name} must be a field name, list, tuple, or field-to-label dict')
    if not all(isinstance(field, str) and field and isinstance(label, str)
               for field, label in pairs):
        raise ValueError(f'{name} field names and labels must be nonempty strings')
    return pairs


def plot_scalar(results, x: str, y=None, *, y2=None, y2label=None,
                y2lim=None, y2scale='linear', labels=None,
                filters=None, include_infeasible=False,
                kind='auto', title=None, xlabel=None, ylabel=None,
                figsize=(8, 5), grid=True, legend=None, legend_title=None,
                xlim=None, ylim=None, xscale='linear', yscale='linear',
                save=None, filename=None, file_format=None, show=None,
                dpi=160, ax=None, **style):
    """Plot multiple scalar fields sharing x; optionally put y2 fields on right.

    y/y2: str, [str, ...], or {field: legend_label}. Missing values are skipped
    per trace, so optional template fields can coexist with other traces.
    xscale, yscale and y2scale accept display divisors or Matplotlib axis types.
    Single traces default to black; multiple traces use the color cycle.
    """
    left = _field_spec(y, 'y')
    right = _field_spec(y2, 'y2')
    if not left and not right:
        raise ValueError('Supply at least one field in y= or y2=')
    if labels is not None:
        if not isinstance(labels, dict):
            raise TypeError('labels must be a dictionary of field names to labels')
        left = [(field, labels.get(field, label)) for field, label in left]
        right = [(field, labels.get(field, label)) for field, label in right]
    if kind not in ('auto', 'line', 'scatter'):
        raise ValueError("kind must be 'auto', 'line', or 'scatter'")

    x_mode, x_divisor = _axis_setting(xscale, 'xscale')
    y_mode, y_divisor = _axis_setting(yscale, 'yscale')
    y2_mode, y2_divisor = _axis_setting(y2scale, 'y2scale')
    fig, axes, owns_axes = _axes(ax, figsize)
    secondary = None
    handles = []
    trace_count = len(left) + len(right)
    colors = plt.rcParams['axes.prop_cycle'].by_key().get('color', ['C0'])
    try:
        for i, (target, (field, field_label), divisor) in enumerate(
                [(axes, pair, y_divisor) for pair in left] +
                [(None, pair, y2_divisor) for pair in right]):
            if target is None:
                if secondary is None:
                    secondary = axes.twinx()
                target = secondary
            points = results.scalar_points(x, field, filters=filters,
                                           include_infeasible=include_infeasible)
            if not points:
                raise ValueError(f'No valid scalar data for x={x!r}, y={field!r}; '
                                 f'available: {results.fields()}')
            plot_style = dict(style)
            plot_style.setdefault('label', field_label)
            if trace_count == 1:
                plot_style.setdefault('color', 'black')
            else:
                plot_style.setdefault('color', colors[i % len(colors)])
            xx = np.asarray([point[0] for point in points], dtype=float) / x_divisor
            yy = np.asarray([point[1] for point in points], dtype=float) / divisor
            selected_kind = ('line' if x in results.parameters else 'scatter') if kind == 'auto' else kind
            if selected_kind == 'line':
                plot_style.setdefault('marker', 'o')
                artist, = target.plot(xx, yy, **plot_style)
            else:
                artist = target.scatter(xx, yy, **plot_style)
            handles.append((artist, field_label))

        axes.set(xlabel=x if xlabel is None else xlabel,
                 ylabel=(left[0][0] if ylabel is None and left else
                         '' if ylabel is None else ylabel),
                 xscale=x_mode, yscale=y_mode)
        if xlim is not None:
            axes.set_xlim(xlim)
        if ylim is not None:
            axes.set_ylim(ylim)
        axes.grid(bool(grid), alpha=0.3)
        if secondary is not None:
            secondary.set(ylabel=(right[0][0] if y2label is None else y2label),
                          yscale=y2_mode)
            if y2lim is not None:
                secondary.set_ylim(y2lim)
        if title is not None:
            axes.set_title(title)
        if legend is None:
            legend = trace_count > 1 or 'label' in style
        if legend:
            axes.legend([item[0] for item in handles],
                        [item[0].get_label() for item in handles], title=legend_title)
        default_name = _filename('scalar', *(field for field, _ in left + right), 'vs', x)
        if owns_axes:
            fig.tight_layout()
        destination = _destination(results, fig, save, filename, file_format, default_name)
        if destination is not None:
            destination.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(destination, dpi=dpi, bbox_inches='tight')
        if show is None:
            show = destination is None and owns_axes
        if show:
            plt.show()
        return fig
    except Exception:
        if owns_axes:
            plt.close(fig)
        raise


def plot_case_history(results, y=None, *, x='time_s', y2=None, case_id='baseline',
                      labels=None, title=None, xlabel=None, ylabel=None,
                      y2label=None, figsize=(9, 5), grid=True, legend=None,
                      legend_title=None, xlim=None, ylim=None, y2lim=None,
                      xscale='linear', yscale='linear', y2scale='linear',
                      save=None, filename=None, file_format=None, show=None,
                      dpi=160, ax=None, **style):
    """Plot multiple history variables for one flight case, with a right y-axis.

    y/y2 can be a field, [fields], or {field: label}. x defaults to time_s.
    Historical data is read only from saved histories.h5; no rerun required.
    """
    left = _field_spec(y, 'y')
    right = _field_spec(y2, 'y2')
    if not left and not right:
        raise ValueError('Supply at least one field in y= or y2=')
    if labels is not None:
        if not isinstance(labels, dict):
            raise TypeError('labels must be a dictionary of field names to labels')
        left = [(field, labels.get(field, label)) for field, label in left]
        right = [(field, labels.get(field, label)) for field, label in right]
    history = results.history(case_id)
    times = history.get(x)
    if times is None:
        raise ValueError(f'{x!r} is not in history for {case_id!r}')
    for field, label in left + right:
        if field not in history:
            raise ValueError(f'{field!r} not available in history for {case_id!r}; '
                             f'available: {list(history)}')
    x_mode, x_divisor = _axis_setting(xscale, 'xscale')
    y_mode, y_divisor = _axis_setting(yscale, 'yscale')
    y2_mode, y2_divisor = _axis_setting(y2scale, 'y2scale')
    fig, axes, owns_axes = _axes(ax, figsize)
    secondary = None
    artists = []
    count = len(left) + len(right)
    colors = plt.rcParams['axes.prop_cycle'].by_key().get('color', ['C0'])
    try:
        for i, (field, label) in enumerate(left + right):
            if i < len(left):
                target, divisor = axes, y_divisor
            else:
                if secondary is None:
                    secondary = axes.twinx()
                target, divisor = secondary, y2_divisor
            line_style = dict(style)
            line_style.setdefault('label', label)
            line_style.setdefault('color', 'black' if count == 1 else colors[i % len(colors)])
            line, = target.plot(np.asarray(times, dtype=float) / x_divisor,
                                np.asarray(history[field], dtype=float) / divisor,
                                **line_style)
            artists.append(line)
        axes.set(xlabel=x if xlabel is None else xlabel,
                 ylabel=(left[0][0] if ylabel is None and left else
                         '' if ylabel is None else ylabel),
                 xscale=x_mode, yscale=y_mode)
        axes.grid(bool(grid), alpha=0.3)
        if xlim is not None:
            axes.set_xlim(xlim)
        if ylim is not None:
            axes.set_ylim(ylim)
        if secondary is not None:
            secondary.set(ylabel=right[0][0] if y2label is None else y2label,
                          yscale=y2_mode)
            if y2lim is not None:
                secondary.set_ylim(y2lim)
        if title is not None:
            axes.set_title(title)
        if legend is None:
            legend = count > 1 or 'label' in style
        if legend:
            axes.legend(artists, [item.get_label() for item in artists], title=legend_title)
        if owns_axes:
            fig.tight_layout()
        destination = _destination(results, fig, save, filename, file_format,
                                   _filename('case_history', case_id, *(field for field, _ in left + right)))
        if destination is not None:
            destination.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(destination, dpi=dpi, bbox_inches='tight')
        if show is None:
            show = destination is None and owns_axes
        if show:
            plt.show()
        return fig
    except Exception:
        if owns_axes:
            plt.close(fig)
        raise


def plot_history(results, y: str, group_by: str, *, filters=None,
                 include_infeasible=False, title=None, xlabel=None, ylabel=None,
                 figsize=(8, 5), grid=True, legend=None, legend_title=None,
                 xlim=None, ylim=None, xscale='linear', yscale='linear',
                 save=None, filename=None, file_format=None, show=None,
                 dpi=160, ax=None, case_labels=None, colorbar=None,
                 colorbar_label=None, cmap='viridis', color_scale=1.0,
                 active_only=False, max_traces=None, **style):
    """Plot flight histories, with a compact colorbar for large numeric sweeps.

    colorbar=None enables the colorbar automatically for >8 curves; with it,
    the automatic legend only shows the black dashed baseline (if present).
    color_scale=1e6 allows pressure values in Pa to display as MPa.
    active_only=True zooms to the final nonzero sample of y across curves.
    max_traces limits clutter by sampling the numeric sweep evenly, including
    the baseline if present. Numeric xscale/yscale divide plotted values;
    color_scale independently controls the sweep-colorbar labels. Neither
    saved histories nor derivative calculations are modified.
    """
    if group_by not in results.parameters:
        raise ValueError(f'{group_by!r} must be an enabled sweep parameter')
    cases = results._select(varying=group_by, filters=filters,
                            include_baseline=results.mode == 'one_at_a_time',
                            include_infeasible=include_infeasible)
    cases = sorted(cases, key=lambda row: float(row[group_by]))
    curves = []
    for row in cases:
        try:
            data = results.history(row['case_id'])
        except KeyError:
            continue
        if y in data and 'time_s' in data:
            curves.append((row, data))
    if not curves:
        raise ValueError(f'No histories with output {y!r}; available: {results.history_fields()}')

    if max_traces is not None:
        if isinstance(max_traces, bool) or not isinstance(max_traces, int) or max_traces < 1:
            raise ValueError('max_traces must be a positive integer or None')
        if len(curves) > max_traces:
            baselines = [item for item in curves if item[0]['is_baseline']]
            others = [item for item in curves if not item[0]['is_baseline']]
            slots = max(0, max_traces - len(baselines))
            if slots:
                indices = np.linspace(0, len(others) - 1, slots).round().astype(int)
                curves = [others[index] for index in indices] + baselines
            else:
                curves = baselines[:max_traces]

    if colorbar is None:
        colorbar = len(curves) > 8 and 'color' not in style
    if colorbar and 'color' in style:
        raise ValueError('colorbar=True cannot be combined with a fixed color=...')
    colored = [item for item in curves if not item[0]['is_baseline']]
    if colorbar and colored:
        colormap, norm = _color_map([row[group_by] for row, _ in colored],
                                    cmap, color_scale)
    else:
        colorbar = False

    x_mode, x_divisor = _axis_setting(xscale, 'xscale')
    y_mode, y_divisor = _axis_setting(yscale, 'yscale')
    fig, axes, owns_axes = _axes(ax, figsize)
    last_active = None
    first_time = None
    # Plot the sweep curves first, then the baseline on top for visibility.
    order = colored + [item for item in curves if item[0]['is_baseline']]
    for row, data in order:
        label = 'baseline' if row['is_baseline'] else f'{group_by}={row[group_by]:g}'
        if case_labels is not None:
            label = case_labels.get(row['case_id'], case_labels.get(row.get(group_by), label))
        line_style = dict(style)
        line_style.setdefault('label', label)
        if colorbar and not row['is_baseline']:
            line_style.setdefault('color', colormap(norm(row[group_by] / color_scale)))
        elif row['is_baseline']:
            line_style.setdefault('color', 'black')
            if len(curves) > 1:
                line_style.setdefault('linestyle', '--')
                line_style.setdefault('linewidth', 2.25)
        else:
            if len(curves) == 1:
                line_style.setdefault('color', 'black')
        times = np.asarray(data['time_s'], dtype=float) / x_divisor
        values = np.asarray(data[y], dtype=float) / y_divisor
        axes.plot(times, values, **line_style)

        if active_only:
            time = times
            finite = np.isfinite(time) & np.isfinite(values)
            if np.any(finite):
                time, values = time[finite], values[finite]
                first = float(np.min(time))
                first_time = first if first_time is None else min(first, first_time)
                magnitude = np.abs(values)
                peak = float(np.max(magnitude))
                if peak > 0:
                    significant = magnitude > peak * 1e-3
                    if np.any(significant):
                        last = float(np.max(time[significant]))
                        last_active = last if last_active is None else max(last, last_active)

    if active_only and xlim is None and last_active is not None:
        start = min(0.0, first_time) if first_time is not None else 0.0
        padding = max(0.5 / x_divisor, 0.08 * (last_active - start))
        xlim = (start, last_active + padding)

    if colorbar:
        _add_colorbar(fig, axes, colormap, norm,
                      colorbar_label if colorbar_label is not None else group_by)
        if legend is None:
            legend = 'baseline'

    return _finish(results, fig, axes, default_xlabel='time_s', default_ylabel=y,
                   default_name=_filename('history', y, 'by', group_by),
                   title=title, xlabel=xlabel, ylabel=ylabel,
                   grid=grid, legend=legend, legend_title=legend_title,
                   xlim=xlim, ylim=ylim, xscale=x_mode, yscale=y_mode,
                   save=save, filename=filename, file_format=file_format,
                   show=show, dpi=dpi, owns_axes=owns_axes)


def plot_derivative(results, x: str, y: str, wrt: str, *, filters=None,
                    include_infeasible=False, kind='line', title=None,
                    xlabel=None, ylabel=None, figsize=(8, 5), grid=True,
                    legend=None, legend_title=None, xlim=None, ylim=None,
                    xscale='linear', yscale='linear', save=None, filename=None,
                    file_format=None, show=None, dpi=160, ax=None, **style):
    """Plot dy/d(wrt) versus x. Axis display scaling does not rederive dy/d(wrt)."""
    values, dydx = results.scalar_derivative(y, wrt, filters=filters,
                                              include_infeasible=include_infeasible)
    if x == wrt:
        abscissa = values
    else:
        cases = results._select(varying=wrt, filters=filters,
                                include_baseline=results.mode == 'one_at_a_time',
                                include_infeasible=include_infeasible)
        coordinates = {row[wrt]: row.get(x) for row in cases}
        if any(not isinstance(coordinates.get(v), (float, int)) for v in values):
            raise ValueError(f'Cannot use {x!r} as derivative plot x-axis')
        abscissa = [coordinates[v] for v in values]
    x_mode, x_divisor = _axis_setting(xscale, 'xscale')
    y_mode, y_divisor = _axis_setting(yscale, 'yscale')
    fig, axes, owns_axes = _axes(ax, figsize)
    try:
        _plot_line_or_scatter(axes,
                              np.asarray(abscissa, dtype=float) / x_divisor,
                              np.asarray(dydx, dtype=float) / y_divisor,
                              kind=kind, style=style)
    except Exception:
        if owns_axes:
            plt.close(fig)
        raise
    return _finish(results, fig, axes, default_xlabel=x,
                   default_ylabel=f'd({y})/d({wrt})',
                   default_name=_filename('derivative', y, 'wrt', wrt, 'vs', x),
                   title=title, xlabel=xlabel, ylabel=ylabel,
                   grid=grid, legend=legend, legend_title=legend_title,
                   xlim=xlim, ylim=ylim, xscale=x_mode, yscale=y_mode,
                   save=save, filename=filename, file_format=file_format,
                   show=show, dpi=dpi, owns_axes=owns_axes)


def plot_history_derivative(results, y: str, wrt: str, *, filters=None,
                            include_infeasible=False, at=None,
                            title=None, xlabel=None, ylabel=None,
                            figsize=(8, 5), grid=True, legend=None,
                            legend_title=None, xlim=None, ylim=None,
                            xscale='linear', yscale='linear',
                            save=None, filename=None, file_format=None,
                            show=None, dpi=160, ax=None, colorbar=None,
                            colorbar_label=None, cmap='viridis', color_scale=1.0,
                            **style):
    """Plot d(history y)/d(wrt) against time; numeric scales affect display only."""
    xs, times, derivative = results.history_derivative(
        y, wrt, filters=filters, include_infeasible=include_infeasible)
    x_mode, x_divisor = _axis_setting(xscale, 'xscale')
    y_mode, y_divisor = _axis_setting(yscale, 'yscale')
    fig, axes, owns_axes = _axes(ax, figsize)
    if at is None:
        indices = range(len(xs))
    else:
        indices = [int(np.argmin(abs(xs - float(at))))]
    if colorbar is None:
        colorbar = len(indices) > 8 and 'color' not in style
    if colorbar and 'color' in style:
        raise ValueError('colorbar=True cannot be combined with a fixed color=...')
    if colorbar:
        colormap, norm = _color_map([xs[index] for index in indices], cmap, color_scale)
    for index in indices:
        line_style = dict(style)
        line_style.setdefault('label', f'{wrt}={xs[index]:g}')
        if colorbar:
            line_style.setdefault('color', colormap(norm(xs[index] / color_scale)))
        elif len(indices) == 1:
            line_style.setdefault('color', 'black')
        axes.plot(np.asarray(times, dtype=float) / x_divisor,
                  np.asarray(derivative[index], dtype=float) / y_divisor,
                  **line_style)
    if colorbar:
        _add_colorbar(fig, axes, colormap, norm,
                      colorbar_label if colorbar_label is not None else wrt)
        if legend is None:
            legend = False
    return _finish(results, fig, axes, default_xlabel='time_s',
                   default_ylabel=f'd({y})/d({wrt})',
                   default_name=_filename('history_derivative', y, 'wrt', wrt),
                   title=title, xlabel=xlabel, ylabel=ylabel,
                   grid=grid, legend=legend, legend_title=legend_title,
                   xlim=xlim, ylim=ylim, xscale=x_mode, yscale=y_mode,
                   save=save, filename=filename, file_format=file_format,
                   show=show, dpi=dpi, owns_axes=owns_axes)
