advanced:
  flight:
    trial_max_retries: 10
    trial_min_dt: 1.0e-06
    corrector_max_iterations: 10
    corrector_tolerance: 1.0e-08
    event_max_iterations: 50
    event_time_tolerance: 1.0e-06
  fluid_network:
    jacobian: colored
    max_step: 1.0
    residual_retries: 3
    residual_tolerance: 1.0e-05
    retry_rtol_factor: 0.1
    retry_rtol_floor: 1.0e-08
    rtol: 1.0e-05
  heating:
    convergence_tolerance: 0.001
    max_iterations: 20
    temperature_tolerance: 0.01
  t_wall_min: 0.001
  tank_pressure_fos: 1.5
  weld_allowable: 234400000.0
  endcap_mass_multiplier: 1.5
aero:
  drag_multiplier: 1.0
  q_cutoff_Pa: 0.01
  finish: 30um
  fins_on_boattail: true
  model: AeroTables/dragmodel.h5
  nose: vonkarman
avi_bay:
  length: 0.25
engine:
  cf_efficiency: 0.95
  cstar_efficiency: 0.9
  exit_pressure: 56732.13275827947
  fuel: RP-1
  length: 0.45
  mass: 18.0
  oxidizer: LOX
environment:
  wind:
    enabled: false
    profile: AeroTables/WindProfiles/RAP_HWM.csv
  altitude_step: 100.0
  max_altitude: 300000.0
fin_can:
  boattail_aft_diameter: 0.2387008240802011
  boattail_length: 0.5751559808898917
  boattail_wall_thickness: 0.00318
  fin_count: 4
  fin_thickness: 0.008613855013331825
  material: carbon_fiber
  root_chord: 0.5030496659340901
  span: 0.37174683042325185
  sweep_fraction: 0.821707283447428
  tip_chord: 0.19315079310328132
inter_tank:
  stringer_count: 4
  stringer_material: aluminum_7075
launch:
  altitude: 1191.0
  rail_height: 15.0
  velocity: 0.0
nosecone:
  wall_thickness: 0.0032
  fineness_ratio: 5.622303724533916
  material: carbon_fiber
  profile: von_karman
  tip_radius: 0.01
prop_system:
  MR_target: 2.0828775332060707
  Pc_target: 1468631.8081285474
  fuel_inj_stiffness: 0.24
  fuel_tank_inj_dp: 275790.291727
  initial_conditions:
    fuel_tank:
      T: 298.15
      fluid: n-Dodecane
      gas_T: 298.15
      gas_fluid: Nitrogen
    ox_tank:
      T: 100.0
      fluid: Oxygen
      gas_T: 293.0
      gas_fluid: Nitrogen
    press_tank:
      T: 298.15
      fluid: Nitrogen
  nozzle_cd: 1.0
  ox_inj_stiffness: 0.24
  ox_tank_inj_dp: 275790.291727
  regulator:
    FUEL_REGULATOR:
      capacity_factor: 5.0
      collapse_factor: 1.2
      tank_id: fuel_tank
    OX_REGULATOR:
      capacity_factor: 5.0
      collapse_factor: 1.4
      tank_id: ox_tank
  template: Configs/templates/pressure_fed_regulator.yaml
  thrust_target: 14710.375938940502
property_models:
  combustion:
    source: table
    table:
      lookup_file: FluidTables/sizer_lookups.h5
      nfz: 2
  pure_fluid:
    source: table
    table:
      fluids:
        Nitrogen:
          pt: nitrogen_pt
          saturation: nitrogen_saturation
        Oxygen: oxygen_pt
        n-Dodecane: ndodecane_pt
      lookup_file: FluidTables/sizer_lookups.h5
simulation:
  dt: 2.0
  fluid_solve_post_shutdown: false
  output: outputs/flight_pressure_fed_regulator.csv
  plot: outputs/flight_pressure_fed_regulator.png
  t_end: 600.0
tanks:
  fuel_tank:
    min_temperature: 80.0
    min_pressure: 68947.57293168
    thermal:
      model: None
    ellipse_ratio: 1.75
    material: aluminum_6061
    passthrough_diameter: 0.0635
    passthrough_wall_thickness: 0.002286
    propellant_mass: 91.94751316814954
    type: propellant
    ullage_factor: 1.1
  ox_tank:
    min_temperature: 80.0
    min_pressure: 68947.57293168
    thermal:
      model: None
    ellipse_ratio: 1.75
    material: aluminum_6061
    passthrough_diameter: 0.0381
    passthrough_wall_thickness: 0.002286
    propellant_mass: 193.66350805755022
    type: propellant
    ullage_factor: 1.1
  press_tank:
    min_pressure: 4136854.3759008
    thermal:
      model: None
    design_pressure: 22801074.35281953
    ellipse_ratio: 1.75
    min_temperature: 180.0
    outer_diameter: 0.2794
    type: pressurant
    construction: copv
    volume: 0.07007841374926453
    thickness_slope: 0.03
    thickness_intercept: 0.004
    equivalent_density: 2238.6
thermal:
  initial_temperature: 288.15
  material_overrides:
    fiberglass:
      specific_heat: 800.0
  sink_temperature: 288.15
vehicle:
  OMLD: 0.31115
  dx: 0.01
  sections:
  - type: nosecone
    masses:
      recovery: 15.0
  - type: avi_bay
    masses:
      cube: 4.0
      clamshell: 1.25
      mounting: 2.0
  - tank_id: press_tank
    type: press_tank
    masses:
      press_tank_shell: 6.89
      mounting: 2.0
      fitting: 1.0
  - length: 0.3302
    type: inter_tank
    masses:
      stringers: 0.88
      clamshell: 1.63
      components: 4.0
      canards: 3.0
    stringer_unit_mass: 0.0
    stiffness_EI: 3270000.0
  - tank_id: ox_tank
    type: prop_tank
    masses: {}
  - length: 0.2794
    type: inter_tank
    masses:
      stringers: 0.74
      clamshell: 1.38
      components: 4.0
    stringer_unit_mass: 0.0
    stiffness_EI: 3270000.0
  - tank_id: fuel_tank
    type: prop_tank
    masses: {}
  - length: 0.3048
    type: inter_tank
    masses:
      stringers: 0.81
      clamshell: 1.5
      main_valves: 4.0
      tubing_solenoids: 3.0
      thrust_structure: 3.0
    stringer_unit_mass: 0.0
    stiffness_EI: 3270000.0
  - type: fin_can
    masses:
      hardware: 2.0
constraints:
  max_length_to_diameter: 35.0
  min_stability_calibers: 2.0
  max_aoa_deg: 15.0
  goal_apogee: 150000.0
  max_burn_duration: 75.0
